FROM creg7smg.azurecr.io/drupal-7-as-an-azure-app-service:base

ENV DRUPAL_HOME "/home/site/wwwroot"

COPY init_container.sh /bin/
COPY sshd_config /etc/ssh/

RUN dos2unix /bin/init_container.sh 

EXPOSE 2222 80

ENV WEBSITE_ROLE_INSTANCE_ID localRoleInstance
ENV WEBSITE_INSTANCE_ID localInstance
ENV PATH ${PATH}:/home/site

WORKDIR /home/site

#CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
ENTRYPOINT ["init_container.sh"]